name: broker_for_testing
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  csv: 6.0.0
  data_table_2: 2.5.10
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: 8.0.3
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_performance: 0.9.4+5
  firebase_performance_platform_interface: 0.1.4+33
  firebase_performance_web: 0.1.6+5
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_secure_storage: 9.2.2
  flutter_secure_storage_linux: 1.2.1
  flutter_secure_storage_macos: 3.1.2
  flutter_secure_storage_platform_interface: 1.1.2
  flutter_secure_storage_web: 1.2.1
  flutter_secure_storage_windows: 3.1.2
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: 1.2.1
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  intl: 0.19.0
  json_path: 0.7.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  substring_highlight: 1.0.33
  synchronized: 3.1.0
  table_calendar: 3.1.1
  timeago: 3.6.1
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  video_player: 2.8.6
  video_player_android: 2.4.16
  video_player_avfoundation: 2.6.1
  video_player_platform_interface: 6.2.2
  video_player_web: 2.3.1
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.0.17
  lints: 4.0.0
  hive_generator: ^1.0.0
  build_runner: ^2.0.0

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#ce1e1e'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
